name: Bug report
description: Report a bug with the exchange rate information or process
body:
  - type: checkboxes
    attributes:
      label: Support guidelines
      description: Please read the support guidelines before proceeding.
      options:
        - label: I've read the [support guidelines](https://github.com/firefly-iii/firefly-iii/blob/main/.github/support.md)
          required: true

  - type: textarea
    attributes:
      label: Description
      description: Please provide a brief description of the issue in 1-2 sentences.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Debug information
      description: Please provide the table from the /debug page of Firefly III. Do not add backticks or quotes.
      placeholder: The output from the /debug page
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Please provide any additional information that seems useful.
