name: Feature request
description: Request a feature or enhancement of the Firefly III exchange rates
body:
  - type: textarea
    attributes:
      label: Description
      description: Please describe your feature request
      placeholder: |
        - I would like Firefly III to do (thing).
        - What if you would add feature (feature here)?
        - Firefly III doesn't do (thing).
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
